# Generated by Django 2.1.1 on 2018-09-09 02:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='query',
            managers=[
                ('c_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
