# Generated by Django 2.1.1 on 2018-09-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180909_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.TextField(),
        ),
    ]
