# Generated by Django 2.1.1 on 2018-09-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180909_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracktrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Query')),
            ],
        ),
    ]
