# Generated by Django 2.1.1 on 2018-09-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180917_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.DateField(max_length=200),
        ),
    ]
