# Generated by Django 2.1.1 on 2018-09-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180917_1616'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='query',
            managers=[
            ],
        ),
    ]
