# Generated by Django 2.1.1 on 2018-09-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180919_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='cError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.TextField(null=True)),
                ('two', models.TextField(null=True)),
            ],
        ),
    ]
